// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return Shalev Osher's professional profile: name, headline, summary, location, and links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          name: "Shalev Osher",
          headline: "Technical Support & DevOps Specialist",
          summary: "Tier 2 Technical Support Specialist at Voicenter with hands-on experience in VoIP, AWS, networking, Linux, and cyber defense. Focused on server administration, API integrations (Kibana), and proactive incident resolution.",
          location: "Israel",
          email: "shalev@osher.cc",
          website: "https://oshercc.lovable.app",
          github: "https://github.com/Shalev-osher",
          linkedin: "https://linkedin.com/in/shalev-osher/"
        })
      }
    ]
  })
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var skills = [
  { area: "Server Management", details: "Linux/Windows server administration, monitoring with PRTG, incident response" },
  { area: "Networking", details: "VoIP, TCP/IP, DNS, routing, troubleshooting production networks" },
  { area: "Databases", details: "SQL, query analysis, data investigation for support cases" },
  { area: "Cloud", details: "Amazon Web Services (AWS) \u2014 EC2, S3, networking, monitoring" },
  { area: "Cyber Defense", details: "Certified Cyber Defense Practitioner (Kernelios / Ministry of Economy)" },
  { area: "Technical Support", details: "Tier 2 support, VIP customers, API integrations via Kibana, QA testing" }
];
var list_skills_default = defineTool2({
  name: "list_skills",
  title: "List skills",
  description: "List the core technical skill areas with a short description for each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(skills) }]
  })
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var experience = [
  {
    company: "Voicenter",
    role: "Technical Support Specialist Tier 2",
    period: "2023 - Present",
    highlights: [
      "Collaborates with Development and DevOps teams via Jira",
      "Supports VIP and standard clients across product suite",
      "Works with API integrations (Kibana), networking, and AWS",
      "Conducts QA on features and servers",
      "Co-developed a troubleshooting tool with Development",
      "Diagnoses live issues across many servers using PRTG"
    ]
  },
  {
    company: "Voicenter",
    role: "Technical Support Specialist - Strategic Customers",
    period: "2021 - 2023",
    highlights: [
      "Supported cloud telephony systems",
      "Wrote guides and presentations, ran apprenticeships",
      "Managed accounts of the largest on-site clients",
      "Worked with ASTERISK and SQL alongside IT/eng/dev"
    ]
  },
  {
    company: "Voicenter",
    role: "Technical Support Engineer Tier 1",
    period: "2021",
    highlights: [
      "Analyzed VoIP networks and computer systems",
      "Resolved VoIP issues via troubleshooting",
      "Improved network security measures and protocols",
      "Provided first-line support via calls, emails, tickets"
    ]
  },
  {
    company: "ILDC",
    role: "Quality Assurance Tester",
    period: "2018 - 2021",
    highlights: [
      "QA in Sagemcom lab for Altice (HOT) products",
      "Daily set-top box quality assurance testing"
    ]
  },
  {
    company: "IDF",
    role: "Military Service",
    period: "2015 - 2018",
    highlights: [
      "Vehicle treatments and test equipment operation",
      "Removed and installed vehicle assemblies per procedure"
    ]
  }
];
var list_experience_default = defineTool3({
  name: "list_experience",
  title: "List work experience",
  description: "List Shalev Osher's work history with role, company, period, and key highlights.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(experience) }]
  })
});

// src/lib/mcp/tools/list-certifications.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var certifications = [
  { name: "Certified Hands-On Cyber Security Specialist", issuer: "Kernelios", code: "CHCSS 310", year: "April 2022" },
  { name: "Cyber Defense Practitioner - Diploma", issuer: "Israel Ministry of Economy and Industry", code: "Certificate #1442431", year: "April 2022" },
  { name: "Cyber Defense Practitioner - Grades", issuer: "Israel Ministry of Economy and Industry", code: "Kernelios Ltd.", year: "June 2022" },
  { name: "MCSA: Windows Server 2016", issuer: "Microsoft", code: "Cert #1F7071-E04B87", year: "November 2020", verifyUrl: "https://learn.microsoft.com/he-il/users/shalevosher-6659/transcript/714gcwjmylnq9k7" },
  { name: "Linux Essentials", issuer: "Linux Professional Institute (LPI)", code: "LPI000494064", year: "July 2021", verifyUrl: "https://cs.lpi.org/caf/Xamman/certification/verify/LPI000494064/rafgerhedt" }
];
var list_certifications_default = defineTool4({
  name: "list_certifications",
  title: "List certifications",
  description: "List professional certifications with issuer, credential code, year, and verification URL when available.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(certifications) }]
  })
});

// src/lib/mcp/tools/list-github-projects.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_github_projects_default = defineTool5({
  name: "list_github_projects",
  title: "List GitHub projects",
  description: "Fetch Shalev Osher's public GitHub repositories, sorted by most recently updated.",
  inputSchema: {
    limit: z.number().int().min(1).max(30).optional().describe("Maximum number of repos to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const n = limit ?? 10;
    const res = await fetch(
      `https://api.github.com/users/Shalev-osher/repos?sort=updated&per_page=${n}`,
      { headers: { Accept: "application/vnd.github+json" } }
    );
    if (!res.ok) {
      return { content: [{ type: "text", text: `GitHub API error: ${res.status}` }], isError: true };
    }
    const repos = await res.json();
    const compact = repos.map((r) => ({
      name: r.name,
      description: r.description,
      url: r.html_url,
      language: r.language,
      stars: r.stargazers_count,
      forks: r.forks_count,
      updated_at: r.updated_at,
      topics: r.topics
    }));
    return { content: [{ type: "text", text: JSON.stringify(compact) }] };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "shalev-osher-portfolio",
  title: "Shalev Osher Portfolio",
  version: "0.1.0",
  instructions: "Public MCP server for Shalev Osher's portfolio. Use these tools to fetch profile info, skills, work experience, certifications, and public GitHub projects. All tools are read-only and expose only intentionally public information.",
  tools: [get_profile_default, list_skills_default, list_experience_default, list_certifications_default, list_github_projects_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
